version: "3"
services:

  reverseproxy:  # see https://docs.traefik.io/#the-traefik-quickstart-using-docker
    image: icoxfog417/executive_button_proxy:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/executive_button
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: reverseproxy
  
  backend:
    image: icoxfog417/executive_button_backend:latest
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000
    command: ["/backend/scripts/run.sh"]
    environment:
      ADMIN_USERNAME: "administrator"
      ADMIN_PASSWORD: "password"
      ADMIN_EMAIL: "admin@example.com"
    tty: true
    stdin_open: true
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/executive_button
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: backend

  frontend:
    image: icoxfog417/executive_button_frontend:latest
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    command: /bin/sh -c "npm run dev"
    environment:
      BACKEND_URL: "http://backend:8000/"
      API_URL_BROWSER: "/api"
    tty: true
    depends_on:
      - backend
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/executive_button
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: frontend
