name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: echo "${DOCKER_HUB_TOKEN}" | docker login -u icoxfog417 --password-stdin

    - name: Build the Docker images
      run: |
        docker-compose build --force-rm
        docker tag executive_button_backend icoxfog417/executive_button_backend
        docker tag executive_button_frontend icoxfog417/executive_button_frontend
        docker push icoxfog417/executive_button_backend:latest
        docker push icoxfog417/executive_button_frontend:latest

    - name: Build proxy Docker images
      run: |
        docker build -f nginx/Dockerfile -t icoxfog417/executive_button_proxy:latest .
        docker push icoxfog417/executive_button_proxy:latest
